version: '3.8'

services:
  backend:
    image: guilhermehvs/backend_fixit:latest
    container_name: backend_fixit
    ports:
      - "8080:8080"
    networks:
      - fixit-network

  frontend:
    image: guilhermehvs/frontend_fixit:latest
    container_name: frontend_fixit
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - fixit-network

networks:
  fixit-network:
    driver: bridge